### ISSUE TITLE
Updated DATASHEET.md with relevant information

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#10]

**Comment by Daniel-Ind** [comment]
Hello @vukosim. 
The following needs to be addressed:

- I am not sure what information to provide on the distribution section of the Datasheet, I have left that section blank to avoid providing misinformation. 
- The uses section, questions: 1, 3, and 5. I believe these questions would best be answered by you or anyone else on the team. These are questions on what the dataset will be used for and what is has already been used for.
- At the very top, the author, must I have written my name? I left that empty and I put the Data Science for Social Impact Research Group (DSFSI) on the organization, I'm not sure if this is fine. 

If there is anything else that you may need, please do communicate and I will avail myself.
