### ISSUE TITLE
Manually Extract 1 story that is in all languages

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#2]
- Check the PDFs and see which story has been extracted in all languages
- Copy and paste the story into 11 files .txt files (1 for each language )
- Develop a naming convention
- Note: Must be able to align sentences in future.
- Push example into repository
- Document any challenges.

**Comment by Daniel-Ind** [comment]
- Second article from the latest Vukuzenzele has been selected as the story.
- Each language has its own .txt file named using proposed naming convention.
- ReadMe included with details on proposed naming convention.
- Pushed to story branch -> data/raw.
