### ISSUE TITLE
Lang Code Mismatch: nso vs sot vs sep 

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/vukuzenzele-nlp#29]
The processed annotations feature txts for both **sep** & **nso**, but none for **sot**

This causes conflicts later in the alignment process when trying to decide which language goes with which language model.

- [ ] Investigate where error originates
- [ ] Is Sesotho under nso? or Sepedi under nso?
- [ ] Figure out & Implement fix

**Comment by vukosim** [comment]
Sepedi is supposed to be NSO. 

Sesotho is supposed to be SOT

Setswana is supposed to be TSN

see https://www.loc.gov/standards/iso639-2/php/code_list.php

@lastrucci01

**Comment by vukosim** [comment]
this affects monolingual as well.

We need to compile a monolingual corpus for SOT urgently.

**Comment by vukosim** [comment]
@AndaniMadodonga how did you choose the language codes?

I think you might have mixed sesotho and sepedi codes.

**Comment by lastrucci01** [comment]
Hey Prof @vukosim 

So if I remember correctly the mistake actually comes from the Vukuzenzele website.
They listed nso as Sesotho and sep as Sepedi, so it is propagated from the raw data. 
I did add a note on the README on Huggingface that this mistake exists and it will be fixed. 
If it is super urgent I can get it done tomorrow, probably just write a quick script that iterates over the files and changes them to the correct conventions.

**Comment by lastrucci01** [comment]
@vukosim Okay I checked the website and I am in fact wrong, although I recall when I downloaded the November & December 2022 ones there was something wrong.}

Nevertheless, I will fix it tomorrow!

**Comment by vukosim** [comment]
Thank you @lastrucci01
