### ISSUE TITLE
Prepare for Crowdsourced Extraction of all parallel stories

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#4]
Prepare a guide for volunteers on extraction of stories

Create and share the guide with me.

**Comment by Daniel-Ind** [comment]
@vukosim 
This is the crowdsourced extraction guide. I was not too sure about the format although I am able to redo or add information to it if there is a need or if a different file extension is needed,


[Crowdsource Extraction guide.pdf](https://github.com/dsfsi/vukuzenzele-nlp/files/9174802/Crowdsource.Extraction.guide.pdf)
